"""
cairn/turn_hook.py — Stop hook (fires ONCE PER TURN, after each response)

Captures the conversation itself — the WHY that tool-call capture misses.
PostToolUse (hook.py) records what the agent DID; this records what was SAID
and DECIDED. A decision made by talking (no tool call) is invisible to the
tool hook — this is the hook that catches it.

Cheap by design: a salience gate + a SQLite write, NO embedding model loaded
(embedding happens later at SessionEnd / the background embedder). It must
never slow or break a turn — every error path exits 0.

Reads the just-finished exchange from the transcript (`transcript_path` in the
Stop event), captures the newest real user turn + agent turn that haven't been
captured yet, salience-gated so greetings/acks ("hi", "thanks", "👍") don't
become nodes. Dedups per turn via a session-scoped marker so a re-fired Stop
(stop_hook_active) can't double-write.

Claude Code settings.json:
  "Stop": [{ "hooks": [{ "type": "command",
    "command": "python -X utf8 <path>/cairn/turn_hook.py", "timeout": 15 }] }]
"""
import sys, os, json, re
from pathlib import Path

# self-contained: add cairn package root to path without needing pip install
sys.path.insert(0, str(Path(__file__).parent.parent))

# pure pleasantries / acknowledgements — never worth a node on their own
_PLEASANTRY = re.compile(
    r"^(?:hi|hey+|hello|yo|sup|thx|thanks|thank you|thank you so much|ty|ok|okay|"
    r"k|kk|cool|nice|got it|gotcha|yep|yup|yeah|sure|np|no problem|sounds good|"
    r"perfect|great|awesome|done|lgtm|cheers|lol|haha+|ok thanks)[\s!.,]*$",
    re.IGNORECASE,
)

# harness-injected "user" turns — text the system puts in the user role that the
# human never typed (post-compaction continuation, local-command caveats). Never
# real signal; must never become nodes. Matched case-insensitively as a prefix.
_HARNESS_USER = (
    "this session is being continued from a previous conversation",
    "caveat: the messages below were generated by the user while running",
    "[request interrupted by user",   # harness interrupt marker — never typed
    # machinery that ARRIVES on the user channel but no human ever typed —
    # the owner found a background-task notice in his brain labeled 'human'
    # (2026-07-03; 188 impostors voided in the sweep that followed):
    "<task-notification>",
    "[system notification",
    "<system-reminder>",
)

# No agent-prose cap here: write_turn (capture.py) bounds the DISPLAY fields and
# preserves the complete text via episodic_full — same lossless pattern as
# codex_hook/importer (owner bar: full capture of whatever is said). The old
# _AGENT_MAX=4000 pre-slice dropped long agent turns' tails at the door.


def _salient(text: str, speaker: str) -> bool:
    """Worth capturing? User directives can be short ('ship it'); agent acks are not."""
    t = (text or "").strip()
    if not t:
        return False
    if speaker == "user" and t.lower().startswith(_HARNESS_USER):
        return False   # harness boilerplate (continuation/caveat), never typed
    if _PLEASANTRY.match(t):
        return False
    if not re.search(r"[A-Za-z0-9]", t):   # emoji / punctuation only
        return False
    return len(t) >= 4 if speaker == "user" else len(t) >= 40


def _text_from_content(content) -> str:
    """Transcript content is a str (typed user msg) or a list of blocks (assistant)."""
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts = []
        for b in content:
            if isinstance(b, dict) and b.get("type") == "text" and b.get("text"):
                parts.append(b["text"])
            # tool_use / tool_result blocks are captured by hook.py — skip here
        return "\n".join(parts)
    return ""


def _is_real_user_turn(entry: dict) -> bool:
    """A typed user message — not a tool_result echoed back into the transcript."""
    if entry.get("type") != "user":
        return False
    content = (entry.get("message") or {}).get("content")
    if isinstance(content, str):
        return True
    if isinstance(content, list):
        return not any(isinstance(b, dict) and b.get("type") == "tool_result"
                       for b in content)
    return False


def main():
    try:
        raw = sys.stdin.read()
        event = json.loads(raw) if raw.strip() else {}
    except Exception:
        sys.exit(0)

    # don't re-enter when our own activity re-triggers Stop
    if event.get("stop_hook_active"):
        sys.exit(0)

    # ── capture mute: per-chat env switch, or global pause marker ─────────────
    if os.environ.get("CAIRN_CAPTURE") == "0":
        sys.exit(0)
    if (Path.home() / ".cairn" / "CAPTURE_OFF").exists():
        sys.exit(0)

    session_id = event.get("session_id") or os.environ.get("CLAUDE_SESSION_ID", "unknown")
    tpath = event.get("transcript_path")
    if not tpath or not Path(tpath).exists():
        sys.exit(0)

    # ── parse transcript JSONL ────────────────────────────────────────────────
    entries = []
    try:
        for ln in Path(tpath).read_text(encoding="utf-8", errors="replace").splitlines():
            ln = ln.strip()
            if not ln:
                continue
            try:
                entries.append(json.loads(ln))
            except Exception:
                continue
    except Exception:
        sys.exit(0)
    if not entries:
        sys.exit(0)

    # latest assistant turn — dedup this whole turn by its uuid
    last_assistant = next((e for e in reversed(entries) if e.get("type") == "assistant"), None)
    a_uuid = (last_assistant or {}).get("uuid") or ""

    cairn_dir = Path.home() / ".cairn"
    cairn_dir.mkdir(parents=True, exist_ok=True)
    pos_file = cairn_dir / f"last_turn_{session_id}.txt"
    already = pos_file.read_text().strip() if pos_file.exists() else ""
    if a_uuid and a_uuid == already:
        sys.exit(0)   # this turn already captured

    last_user = next((e for e in reversed(entries) if _is_real_user_turn(e)), None)

    # ── aggregate this turn's token usage from the transcript ────────────────
    # Tokens live on the assistant messages since the last real user turn.
    # output/input/cache_write are per-message (additive); cache_read is the
    # standing context size, so take the last value, not a sum.
    usage = None
    try:
        lui = -1
        for i in range(len(entries) - 1, -1, -1):
            if _is_real_user_turn(entries[i]):
                lui = i
                break
        agg = {"input_tokens": 0, "output_tokens": 0,
               "cache_creation_input_tokens": 0, "cache_read_input_tokens": 0}
        seen = False
        for e in entries[lui + 1:]:
            if e.get("type") != "assistant":
                continue
            u = (e.get("message") or {}).get("usage") or {}
            if not u:
                continue
            seen = True
            agg["input_tokens"]  += int(u.get("input_tokens") or 0)
            agg["output_tokens"] += int(u.get("output_tokens") or 0)
            agg["cache_creation_input_tokens"] += int(u.get("cache_creation_input_tokens") or 0)
            if u.get("cache_read_input_tokens"):
                agg["cache_read_input_tokens"] = int(u["cache_read_input_tokens"])
        usage = agg if seen else None
    except Exception:
        usage = None

    from cairn.capture import write_turn
    from cairn.vault import Vault
    v = Vault()

    def _already_user(text):
        # The UserPromptSubmit hook (prompt_hook.py) normally captured this turn
        # already, at SEND time with the right timestamp. Skip it here so we never
        # double-write — this sweep is only the FALLBACK for a prompt the send-time
        # hook missed (e.g. it errored) or a turn cut short before Stop. Prefix LIKE
        # tolerates trailing-whitespace differences between the two capture paths.
        try:
            pre = (text or "").strip()[:80].replace("%", "").replace("_", "")
            if not pre:
                return False
            return v.conn.execute(
                "SELECT 1 FROM nodes WHERE kind='conversation_turn' AND speaker='user' "
                "AND query LIKE ? LIMIT 1", (pre + "%",)).fetchone() is not None
        except Exception:
            return False

    # Sweep EVERY salient user turn not yet captured — not just the latest. A turn
    # cut short by an interrupt never fired its own Stop, so its message would be
    # skipped when the next Stop grabs only the newest one. We track the last
    # captured user uuid and capture everything after it. First run (no marker):
    # latest only, so we don't re-sweep already-recorded history.
    user_pos = cairn_dir / f"last_user_{session_id}.txt"
    seen_user = user_pos.read_text().strip() if user_pos.exists() else ""
    real_users = [e for e in entries if _is_real_user_turn(e)]
    if seen_user:
        start = next((i + 1 for i, e in enumerate(real_users) if e.get("uuid") == seen_user), 0)
        pending_users = real_users[start:]
    else:
        pending_users = real_users[-1:]

    captured = 0
    try:
        for ue in pending_users:
            utext = _text_from_content((ue.get("message") or {}).get("content"))
            if _salient(utext, "user") and not _already_user(utext):
                write_turn(utext, speaker="user", session=session_id, vault=v)
                captured += 1
        if real_users:
            try:
                user_pos.write_text(real_users[-1].get("uuid") or "")
            except Exception:
                pass
        # 5a: drain this session's buffered tool calls ONCE per turn — they
        # belong to the exchange that just ended regardless of whether the
        # agent prose is salient, so always clear the buffer (don't let a
        # non-salient turn's tools leak into the next turn's node).
        from cairn.pending import drain as _drain_tools
        pending_tools = _drain_tools(session_id)

        if last_assistant is not None:
            amsg = last_assistant.get("message") or {}
            atext = _text_from_content(amsg.get("content"))
            amodel = amsg.get("model") or "unknown"   # the REAL model for this turn
            if _salient(atext, "agent"):
                write_turn(atext, speaker="agent", session=session_id,
                           usage=usage, model=amodel, vault=v,
                           tool_calls=pending_tools or None)
                captured += 1
    except Exception:
        pass  # capture must never break the turn

    # mark this turn handled even if nothing was salient (don't rescan it)
    if a_uuid:
        try:
            pos_file.write_text(a_uuid)
        except Exception:
            pass

    if captured:
        print(f"cairn: captured {captured} conversation turn(s)")
    sys.exit(0)


if __name__ == "__main__":
    main()
